export const currentMarketMockData = {
  adjustmentSettings: undefined,
  calculateSettings: undefined,
  cashPool: 0,
  cashPoolAchHoldDays: '',
  cashPoolSettings: undefined,
  clearAdjustments: false,
  clearOnlyPastDueAdjustments: false,
  collectionPadding: '',
  collectionRule: '',
  created: '',
  creditLineAchHoldDays: '',
  floatDays: 0,
  gamingSettings: [],
  id: 0,
  includeWeekendsWithFloatDays: false,
  internalRestriction: { maxDPE: 0 },
  isDiscountDefaultBidType: false,
  isDiscountMarket: false,
  isEnabled: false,
  isStaticMarket: false,
  isTpf: false,
  makerId: 0,
  marketType: '',
  maxApr: 0,
  maxDiscount: '',
  maximumLoanTerm: '',
  minReturnAmount: 0,
  minimumDpe: 0,
  minimumIncomeAmount: 0,
  name: '',
  nextClearTime: '',
  nextClearTimeRRule: { rrule: '' },
  payDate: '',
  payDateRRule: { rrule: '' },
  prevClearTime: '',
  restriction: '',
  returnAmount: 0,
  sequenceInvoices: false,
  supplierCreditLine: '',
  timezone: '',
  updated: '',
  uuid: '',
  wasClearTimePushed: false,
  currency: 'USD',
  stats: {
    marketId: 27,
    marketUuid: 'ce05a711 - b90e - 40dc-bca0 - 527eab17dd36',
    makerOrganizationUuid: '725e6489 - 5abd-4840 - b3a9 - a62a47b0fd40',
    cashPoolUsed: 0,
    reservedAdjustmentAmount: -384,
    reservedAdjustmentCount: 1,
    matchedAdjustmentAmount: 0,
    matchedAdjustmentCount: 0,
    unmatchedAdjustmentAmount: -17462.94,
    unmatchedAdjustmentCount: 6,
    acceptedInvoiceAmount: 0,
    acceptedInvoiceCount: 0,
    acceptedMinApr: null,
    acceptedMaxApr: null,
    acceptedTakerCount: 0,
    awardedInvoiceAmount: 0,
    awardedDiscountedAmount: 0,
    awardedInvoiceCount: 0,
    awardedTakerCount: 0,
    blendedClearingDiscountWeightedAvg: 0,
    availableInvoiceCount: 77,
    availableTakerCount: 14,
    availableDiscountWeightedAvg: null,
    overallEarn: 0,
    overallAvgDiscount: 0,
    overallAvgDpe: 0,
    overallAvgApr: 0,
    notAcceptedInvoiceCount: 77,
    notAcceptedMinApr: 3,
    notAcceptedMaxApr: 13.5,
    notAcceptedTakerCount: 14,
    pendingInvoiceAmount: 0,
    pendingEarn: 0,
    id: 27,
    makerId: 13865,
    uuid: 'ce05a711 - b90e - 40dc-bca0 - 527eab17dd36',
    isTpf: false,
    currency: 'CNY',
    acceptedDiscountWeightedAvg: 0,
    awardedDiscountWeightedAvg: 0,
    notAcceptedDiscountWeightedAvg: 0.59,
    pendingDiscountWeightedAvg: 0,
    pendingDpeWeightedAvg: 0,
    pendingAprWeightedAvg: 0,
    overallInvoiceAmount: 0,
    // starts here
    awardedDpeWeightedAvg: 3,
    awardedAprWeightedAvg: 6.4,
    awardedEarn: 9330,
    acceptedDpeWeightedAvg: 10,
    acceptedAprWeightedAvg: 20,
    acceptedEarn: 100,
    notAcceptedInvoiceAmount: 2796909.7,
    notAcceptedDpeWeightedAvg: 39.08,
    notAcceptedEarn: 16475.45,
    notAcceptedAprWeightedAvg: 5.6,
    blendedClearingEarn: 389,
    blendedClearingAprWeightedAvg: 4.5,
    blendedClearingDpeWeightedAvg: 43,
    blendedClearingInvoiceAmount: 578,
    availableEarn: 16475.45,
    availableAprWeightedAvg: 5.6,
    availableDpeWeightedAvg: 39.08,
    availableInvoiceAmount: 2796909.7,
    blendedClearingDiscountedAmount: 977,
    blendedClearingTakerCount: 5,
    blendedClearingInvoiceCount: 100,
    pendingDiscountedAmount: 89773.5,
    pendingInvoiceCount: 67,
    pendingTakerCount: 90,
    overallDiscountedAmount: 896552,
    overallTakerCount: 8,
    overallInvoiceCount: 28,
  },
  clearHistory: [
    {
      payDate: '2020-04-01',
      awardedEarn: 0,
      acceptedEarn: 50400.62,
      clearedAprWeightedAvg: 7.572621,
    },
    {
      payDate: '2020-04-03',
      awardedEarn: 0,
      acceptedEarn: 28883.69,
      clearedAprWeightedAvg: 7.6783,
    },
    {
      payDate: '2020-04-08',
      awardedEarn: 3277.89,
      acceptedEarn: 55038.86,
      clearedAprWeightedAvg: 7.324194,
    },
    {
      payDate: '2020-04-10',
      awardedEarn: 0,
      acceptedEarn: 29739.3,
      clearedAprWeightedAvg: 10.356408,
    },
    {
      payDate: '2020-04-17',
      awardedEarn: 0,
      acceptedEarn: 91245.45,
      clearedAprWeightedAvg: 13.855972,
    },
    {
      payDate: '2020-04-22',
      awardedEarn: 0,
      acceptedEarn: 30141.31,
      clearedAprWeightedAvg: 7.579671,
    },
  ],
};
